baseurl = "https://www.sortee.org"
title = "SORTEE"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""


# Define the number of posts per page
paginate = 6

[menu]

# Main menu

[[menu.main]]
    identifier = "join"
    name = "Join"
    url = "/join/"
    weight = 10

[[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"
    weight = 20

[[menu.main]]
    identifier = "documents"
    name = "Documents"
    url = "/documents/"
    weight = 30

[[menu.main]]
    parent = "documents"
    name = "Awards"
    url = "/awards/"

[[menu.main]]
    parent = "documents"
    name = "Bylaws"
    url = "/bylaws/"

[[menu.main]]
    parent = "documents"
    name = "Code of conduct"
    url = "/codeofconduct/"

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    url = "/resources/"
    weight = 50

[[menu.main]]
    parent = "resources"
    name = "Newsletters"
    url = "/newsletters/"
    weight = 50

[[menu.main]]
    parent = "resources"
    name = "Infographics"
    url = "/infographics/"
    weight = 60

[[menu.main]]
    parent = "resources"
    name = "Reading"
    url = "/reading/"
    weight = 70

[[menu.main]]
    parent = "resources"
    name = "Translations"
    url = "/translations/"
    weight = 80

[[menu.main]]
    parent = "resources"
    name = "Other resources"
    url = "/other_resources/"
    weight = 90

[[menu.main]]
    identifier = "events"
    name = "Events"
    url = "/events/"
    weight = 60

[[menu.main]]
    parent = "events"
    name = "SORTEE workshops and webinars"
    url = "/other_events/"
    weight = 110

[[menu.main]]
    parent = "events"
    name = "Upcoming SORTEE conference"
    url = "/upcoming/"
    weight = 120

[[menu.main]]
    parent = "events"
    name = "Past SORTEE conferences"
    url = "/past/"
    weight = 130

[[menu.main]]
    parent = "events"
    name = "SORTEE meet-ups at other conferences"
    url = "/meet-ups/"
    weight = 140

[[menu.main]]
    parent = "events"
    name = "Online social mixers"
    url = "/mixers/"
    weight = 150

[[menu.main]]
    parent = "events"
    name = "Code club"
    url = "/code_club/"
    weight = 160

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 70

[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 80

[[menu.main]]
    identifier = "supporters"
    name = "Supporters"
    url = "/supporters/"
    weight = 75

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/sortecoevo/sortee"
    pre = "<i class='fab fa-2x fa-github'></i>"

#[[menu.topbar]]
#    weight = 2
#    name = "Facebook"
#    url = "http://facebook.com"
#    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 1
    name = "X"
    url = "https://twitter.com/sortecoevo"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 2
    name = "Mastodon"
    url = "https://ecoevo.social/@sortee"
    pre = "<i class='fab fa-2x fa-mastodon'></i>"

[[menu.topbar]]
    weight = 3
    name = "Linkedin"
    url = "https://www.linkedin.com/company/sortee/"
    pre = "<i class='fab fa-2x fa-linkedin'></i>"

[[menu.topbar]]
    weight = 4
    name = "Bluesky"
    url = "https://bsky.app/profile/sortee.bsky.social"
    pre = "<i class='fa fa-2x fa-square'></i>"

[[menu.topbar]]
    weight = 5
    name = "Instagram"
    url = "https://www.instagram.com/sortecoevo"
    pre = "<i class='fab fa-2x fa-instagram'></i>"

[[menu.topbar]]
    weight = 6
    name = "Youtube"
    url = "https://www.youtube.com/@SORTEcoEvo"
    pre = "<i class='fab fa-2x fa-youtube'></i>"

[[menu.topbar]]
    weight = 7
    name = "Email"
    url = "mailto:sortecoevo@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "SORTEE"
    defaultKeywords = ["blog", "general", "news"]
    mainSections = ["blog"]
    defaultDescription = "SORTEE blog"

    # Social media
    #facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "SORTEcoEvo" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/SORTEE_logo_twitter.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    #enableGoogleMaps = true
    #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    #latitude = "-12.043333"
    #longitude = "-77.028333"

    #Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    # email = "f/mvovbvvz"
    # contact_form_ajax = false

    #about_us = "<p>SORTEE stands for society for Open Reliable Transparent Ecology and Evolutionary biology.</p>"
    copyright = "Copyright (c) 2024, SORTEE; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p>Email: sortecoevo@gmail.com
        <br>Twitter: @SORTEcoEvo
        <br>Mastodon: @SORTEE@ecoevo.social
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.testimonials]
    enable = true #change to true to display
    icon = "fas fa-globe"
    title = "Become a SORTEE volunteer!"
    subtitle = "Nominations close October 30th"
    link_url = "https://tinyurl.com/volunteerSORTEE2025"
    link_text = "https://tinyurl.com/volunteerSORTEE2025"
    
[params.new_news]
    enable = true #change to true to display
    icon = "fas fa-globe"
    title = "2024 SORTEE conference 15-16th October"
    subtitle = "Registration now open and program online!"
    link_url = "/upcoming"
    link_text = "Read more"

[params.see_more]
    enable = true
    icon = "fas fa-egg"
    title = "Society for Open, Reliable, and Transparent Ecology and Evolutionary biology (SORTEE)"
    subtitle = "SORTEE is a service organization that brings together researchers working to improve reliability and transparency through cultural and institutional changes in ecology, evolutionary biology, and related fields broadly defined. Anyone interested in improving research in these disciplines is welcome to join, regardless of experience. The society is international in scope, membership, and objectives."
    link_url = "/join"
    link_text = "Join"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Submit a preprint"
    subtitle = "EcoEvoRxiv is the official preprint server of SORTEE"
    title_2 = "Order a t-shirt"



